AWSTemplateFormatVersion: "2010-09-09"
Description: "Queue to hold UDN joint calling jobs for processing"
Resources:
    UdnSentieonBwaMemQueue:
        Type: AWS::SQS::Queue 
        Properties: 
            MessageRetentionPeriod: 1209600
            QueueName: 'udn-sentieon-bwa-mem'
            VisibilityTimeout: 43200
    UdnAddReadGroupsQueue:
        Type: AWS::SQS::Queue 
        Properties: 
            MessageRetentionPeriod: 1209600
            QueueName: 'udn-add-read-groups'
            VisibilityTimeout: 43200
    UdnMergeBamsQueue:
        Type: AWS::SQS::Queue 
        Properties: 
            MessageRetentionPeriod: 1209600
            QueueName: 'udn-merge-bams'
            VisibilityTimeout: 43200
    UdnSentieonDedupQueue:
        Type: AWS::SQS::Queue 
        Properties: 
            MessageRetentionPeriod: 1209600
            QueueName: 'udn-sentieon-dedup'
            VisibilityTimeout: 43200
    UdnHaplotypeCallerQueue:
        Type: AWS::SQS::Queue 
        Properties: 
            MessageRetentionPeriod: 1209600
            QueueName: 'udn-haplotype-caller'
            VisibilityTimeout: 43200
